apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ida1hzmtv-go
  janus-idp.io/tekton: ida1hzmtv-go
  backstage.io/kubernetes-id: ida1hzmtv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ida1hzmtv-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
